version: '3.7'

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./audio/:/app/audio/
      - ./transcripts/:/app/transcripts/
    ports:
      - 8000:8000
    # environment:
    #   - SPEECH_KEY=
    #   - SPEECH_REGION=
    # depends_on:
    #   - nothing

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi

volumes:
  postgres_data_movie:
  postgres_data_cast: